2 change contact area calculation of threerollpasses
pyroll-project/pyroll-zouhar-contact pull request #3
Opened 2024-08-21 06:32 UTC by RichardPfr

Changed the Contact area calculation so that its more representative for three-roll rolling.

Currently there is also a factor 0.999 necessary to correctly calculate the in_profile local_width - probably due to small numerical deviations.

2024-08-21 07:21 UTC, ChRen95 commented
Without further review of the code, the proposed tests still yield errors. 

See:

FAILED             [100%]
test_contact_area.py:51 (test_plotted_contact_area_3fold)
self = PassSequence(in_profile=InProfile(classifiers={'round'}, cross_section=Polygon(area=0.000313654849054594, height=0.02,... zouhar_contact_c1=0.45, zouhar_contact_c2=0.18, zouhar_contact_c3=1, zouhar_contact_in_width=0.00040710935249972473)])

    def _solve_subunits(self):
        if self._subunits:
            last_profile = self.in_profile
    
            for u in self._subunits:
                try:
>                   last_profile = u.solve(last_profile)

../.venv/lib/python3.12/site-packages/pyroll/core/unit/unit.py:167: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../.venv/lib/python3.12/site-packages/pyroll/core/unit/unit.py:189: in solve
    current_results = self.get_root_hook_results()
../.venv/lib/python3.12/site-packages/pyroll/core/roll_pass/roll_pass.py:159: in get_root_hook_results
    super_results = super().get_root_hook_results()
../.venv/lib/python3.12/site-packages/pyroll/core/unit/unit.py:157: in get_root_hook_results
    self_results = self.evaluate_and_set_hooks()
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:466: in evaluate_and_set_hooks
    return list(_gen())
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:450: in _gen
    result = h.get_result(self)
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:277: in get_result
    result = f(instance)
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:77: in __call__
    result = self.function(instance, **extra_args)
../.venv/lib/python3.12/site-packages/pyroll/core/roll_pass/hookimpls/roll_pass.py:46: in roll_force
    return (self.in_profile.flow_stress + 2 * self.out_profile.flow_stress) / 3 * self.roll.contact_area
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:163: in __get__
    return hook.__get__(instance, owner)
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:202: in __get__
    result = self.get_result(instance)
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:277: in get_result
    result = f(instance)
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:77: in __call__
    result = self.function(instance, **extra_args)
../pyroll/zouhar_contact.py:79: in contact_area
    out_width = rp.out_profile.contact_lines[1].width
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:163: in __get__
    return hook.__get__(instance, owner)
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:202: in __get__
    result = self.get_result(instance)
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:277: in get_result
    result = f(instance)
../.venv/lib/python3.12/site-packages/pyroll/core/hooks.py:77: in __call__
    result = self.function(instance, **extra_args)
../.venv/lib/python3.12/site-packages/pyroll/core/roll_pass/hookimpls/deformation_unit.py:100: in contact_contour_lines
    upper_contact_contour = linemerge(upper_groove_cl.intersection(self.cross_section.exterior))
../.venv/lib/python3.12/site-packages/shapely/ops.py:105: in linemerge
    source = MultiLineString([ls.coords for ls in lines.geoms])
../.venv/lib/python3.12/site-packages/shapely/geometry/multilinestring.py:50: in __new__
    line = linestring.LineString(lines[i])
../.venv/lib/python3.12/site-packages/shapely/geometry/linestring.py:73: in __new__
    geom = shapely.linestrings(coordinates)
../.venv/lib/python3.12/site-packages/shapely/decorators.py:77: in wrapped
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

coords = array([[0.00908349, 0.00124419]]), y = None, z = None, indices = None
out = None, kwargs = {}

    @multithreading_enabled
    def linestrings(coords, y=None, z=None, indices=None, out=None, **kwargs):
        """Create an array of linestrings.
    
        This function will raise an exception if a linestring contains less than
        two points.
    
        Parameters
        ----------
        coords : array_like
            An array of lists of coordinate tuples (2- or 3-dimensional) or, if ``y``
            is provided, an array of lists of x coordinates
        y : array_like, optional
        z : array_like, optional
        indices : array_like, optional
            Indices into the target array where input coordinates belong. If
            provided, the coords should be 2D with shape (N, 2) or (N, 3) and
            indices should be an array of shape (N,) with integers in increasing
            order. Missing indices result in a ValueError unless ``out`` is
            provided, in which case the original value in ``out`` is kept.
        out : ndarray, optional
            An array (with dtype object) to output the geometries into.
        **kwargs
            See :ref:`NumPy ufunc docs <ufuncs.kwargs>` for other keyword arguments.
            Ignored if ``indices`` is provided.
    
        Examples
        --------
        >>> linestrings([[[0, 1], [4, 5]], [[2, 3], [5, 6]]]).tolist()
        [<LINESTRING (0 1, 4 5)>, <LINESTRING (2 3, 5 6)>]
        >>> linestrings([[0, 1], [4, 5], [2, 3], [5, 6], [7, 8]], indices=[0, 0, 1, 1, 1]).tolist()
        [<LINESTRING (0 1, 4 5)>, <LINESTRING (2 3, 5 6, 7 8)>]
    
        Notes
        -----
        - Usage of the ``y`` and ``z`` arguments will prevents lazy evaluation in ``dask``.
          Instead provide the coordinates as a ``(..., 2)`` or ``(..., 3)`` array using only ``coords``.
        """
        coords = _xyz_to_coords(coords, y, z)
        if indices is None:
>           return lib.linestrings(coords, out=out, **kwargs)
E           shapely.errors.GEOSException: IllegalArgumentException: point array must contain 0 or >1 elements

../.venv/lib/python3.12/site-packages/shapely/creation.py:119: GEOSException

The above exception was the direct cause of the following exception:

    def test_plotted_contact_area_3fold():
        import pyroll.zouhar_contact
    
        p: Profile = Profile.round(
            diameter=20e-3,
            temperature=1200 + 273.15,
            material=["C45", "Steel"],
            length=1,
            flow_stress=100e6
        )
    
        ps: PassSequence = PassSequence(
            [
                ThreeRollPass(
                    label="Pass1",
                    roll=Roll(
                        groove=CircularOvalGroove(
                            r1=1e-3,
                            r2=12e-3,
                            depth=3.3e-3,
                            pad_angle=30
                        ),
                        nominal_radius=150e-3,
                        rotational_frequency=1,
                    ),
                    inscribed_circle_diameter=18e-3
                )])
    
>       ps.solve(p)

test_contact_area.py:80: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../.venv/lib/python3.12/site-packages/pyroll/core/unit/unit.py:186: in solve
    self._solve_subunits()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = PassSequence(in_profile=InProfile(classifiers={'round'}, cross_section=Polygon(area=0.000313654849054594, height=0.02,... zouhar_contact_c1=0.45, zouhar_contact_c2=0.18, zouhar_contact_c3=1, zouhar_contact_in_width=0.00040710935249972473)])

    def _solve_subunits(self):
        if self._subunits:
            last_profile = self.in_profile
    
            for u in self._subunits:
                try:
                    last_profile = u.solve(last_profile)
                except Exception as e:
>                   raise RuntimeError(f"Solution of sub units failed at unit {u}.") from e
E                   RuntimeError: Solution of sub units failed at unit ThreeRollPass 'Pass1'.

../.venv/lib/python3.12/site-packages/pyroll/core/unit/unit.py:169: RuntimeError

2024-08-21 07:39 UTC, RichardPfr commented
Sry didnt mention:
To have these changes on the zouhar package work the changes made in pyroll-project/pyroll-core#241 are also required, as the updated contact_lines property is required. 
In my venv i included those changes with a .whl.

I suppose thats where the error comes from, but if not i can have a closer look again.

2024-08-21 13:09 UTC, axtimhaus commented on pyroll/zouhar_contact.py
> +        if "3fold" in rp.classifiers:
Maybe you can avoid such checks if you would define a new hook function for TRP only. Refactor the main logic to a simple function which is called from the respective hook impl. Then you would not need the core changes (removal of TRP default hook impls there).

2024-08-22 11:15 UTC, RichardPfr commented
Added the ThreeRollPass handling to a separate Hook function - but i dont know what you specifically mean with not needing the core changes now? (or is this already clarified with the changes i did there?)

2024-08-22 13:35 UTC, ChRen95 commented
Did you resolve everything?

> Added the ThreeRollPass handling to a separate Hook function - but i dont know what you specifically mean with not needing the core changes now? (or is this already clarified with the changes i did there?)

2024-08-22 15:10 UTC, axtimhaus requested changes
This code is highly duplicated. Refactor it to a function that is called by the hooks

2024-08-22 15:12 UTC, axtimhaus commented
> Added the ThreeRollPass handling to a separate Hook function - but i dont know what you specifically mean with not needing the core changes now? (or is this already clarified with the changes i did there?)

With this two hooks you circumvent the problem with the precedence of the hooks in the core for 3RP

2024-09-16 13:16 UTC, ChRen95 approved these changes

2024-09-16 13:16 UTC, ChRen95 commented
I think also the comments by @axtimhaus are resolved. So please proceed.

2024-10-25 05:40 UTC, merged